[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "./server"

[services.variables]
PORT = "8000"